### ISSUE TITLE
Org.WebRtc => JavaScript runtime error: 'Org' is undefined

### ISSUE THREAD

**Issue by RCapGH** [webrtc-uwp/AppRTC#1]
Hello,
I'm quite new using WebRTC and I would realize a simple video chat between a web client and an app on HoloLens, that's why I chose this UWP application.
But I have one issue when I start the application on my local computer, Org isn't recognized.
(In js\webrtc_WinJS_api.js line 11)
I tried adding the reference using "Install-Package WebRTC" but I still have the problem.
Any idea ?
Thank you, regards

**Comment by SergioOpenPeer** [comment]
For which platform are you trying to run AppRtc?

**Comment by RCapGH** [comment]
Hi,
Thank you for answering but I found the solution.
I solved it restoring packages via the command line "nuget restore" instead of downloading a new webrtc package
